server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
    timeout: 2592000
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/campusecho?useSSL=false
      username: root
      password: kanghui01
  shardingsphere:
    datasource:
      names: campusecho
      campusecho:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/campusecho?useSSL=false
        username: root
        password: kanghui01
    rules:
      sharding:
        sharding-algorithms:
          following_inline:
            type: INLINE
            props:
              algorithm-expression: following_$->{from_user_id % 2}
          follower_inline:
            type: INLINE
            props:
              algorithm-expression: follower_$->{to_user_id % 2}
        tables:
          following:
            actual-data-nodes: campusecho.following_$->{0..1}
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
            table-strategy:
              standard:
                sharding-column: from_user_id
                sharding-algorithm-name: following_inline
          follower:
            actual-data-nodes: campusecho.follower_$->{0..1}
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
            table-strategy:
              standard:
                sharding-column: to_user_id
                sharding-algorithm-name: follower_inline

dubbo:
  application:
    name: user-service
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 20881

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.hgc.campusechocommon.config.StringArrayTypeHandler
  configuration:
    # 开启a_column  到  aColumn 的映射
    map-underscore-to-camel-case: true
#seata:
#  application-id: 8082

